barang/urls.py
from django.urls import path
from .views import create_barang, daftar_barang, detail_barang, get_barang_list, delete_barang

urlpatterns = [
    path('create_barang', create_barang, name='create_barang'),
    path('daftar_barang/', daftar_barang, name='daftar_barang'),
    path('daftar_barang/?page=<int:page_number>', daftar_barang, name='daftar_barang_pagination'),
    path('detail_barang/<int:id_barang>', detail_barang, name='detail_barang_second'),
    path('get_barang_list', get_barang_list, name='get_barang_list'),
    path('delete_barang', delete_barang, name='delete_barang'),
]

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.chat, name='chat'),
    path('<tujuan>', views.chat, name='chat_tujuan'),
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('register/', include('register.urls')),
    path('item/', include(('item.urls','item'),namespace='item')),
    path('profil/', include('profil.urls')),
    path('pesanan/', include(('pesanan.urls','pesanan'),namespace='pesanan')),
    path('level/', include(('level.urls','level'),namespace='level')),
    path('barang/', include(('barang.urls','barang'),namespace='barang')),
    path('chat/', include('chat.urls')),
]

barang/models.py
from django.db import models

# Create your models here.

barang/forms.py
from django import forms
from django.db import connection


def get_item_list():
    cursor = connection.cursor()
    sql = "select nama from toys_rent.item"
    cursor.execute(sql)
    list_nama_item = cursor.fetchall()
    return list_nama_item

# TODO
def get_pemilik_list():
    cursor = connection.cursor()
    sql = "SELECT no_ktp, nama_lengkap FROM toys_rent.anggota NATURAL JOIN toys_rent.pengguna"
    cursor.execute(sql)
    list_nama_pengguna = cursor.fetchall()
    return list_nama_pengguna


# beberapa ada yang diset default, perlu diatur
# beberapa ada yang ambil data dari db, perlu diatur
class Barang_Form(forms.Form):
    # untuk input id
    attrs_id = {
        'class': 'form-control',
        'placeholder': 'Masukan ID barang',
        'id': 'form_ID'
    }
    id_input = forms.CharField(
        label='ID Barang',
        required=True,
        max_length=10, 
        widget=forms.TextInput(attrs=attrs_id)
    )

    # untuk input nama item
    attrs_select = {
        'class': 'custom-select',
        'placeholder': 'Masukan warna barang',
        'id': 'form_item'
    }
    # perlu antisipasi item kosong
    list_nama_item = get_item_list() 
    list_nama_item_real = []
    for x in list_nama_item:
        for y in x:
            list_nama_item_real.append(((y),(y)))
    item_input = forms.ChoiceField(
        label='Nama Item',
        choices=list_nama_item_real,
        required=True,
        widget=forms.Select(attrs=attrs_select)
    )

    # untuk input warna
    attrs_warna = {
        'class': 'form-control',
        'placeholder': 'Masukan warna barang',
        'id': 'form_warna'
    }
    warna_input = forms.CharField(
        label='Warna',
        max_length=50,
        required=False,
        widget=forms.TextInput(attrs=attrs_warna)
    )

    # untuk input url
    attrs_url = {
        'class': 'form-control',
        'placeholder': 'Masukan url foto',
        'id': 'form_url'
    }
    url_input = forms.URLField(
        label='URL foto',
        required=False,
        widget=forms.TextInput(attrs=attrs_url)
    )

    # untuk input kondisi
    # kondisi bisa dibuat default ?
    attrs_kondisi = {
        'class': 'form-control',
        'placeholder': 'Masukan kondisi barang',
        'id': 'form_kondisi'
    }
    kondisi_input = forms.CharField(
        label='Kondisi',
        required=True,
        widget=forms.TextInput(attrs=attrs_kondisi)
    )

    # untuk input lama penggunaan
    attrs_lama_penggunaan = {
        'class': 'form-control',
        'placeholder': 'Masukan lama penggunaan',
        'id': 'form_lama_penggunaan'
    }
    lama_penggunaan_input = forms.IntegerField(
        label='Lama Penggunaan',
        required=False,
        widget=forms.TextInput(attrs=attrs_lama_penggunaan)
    )

    # untuk input nomor ktp
    # nomor ktp pemilik: max_length=20, ambil dari profil
    attrs_select_pemilik = {
        'class': 'custom-select',
        'placeholder': 'Nomor KTP Pemilik',
        'id': 'form_warna'
    }
    list_pemilik = get_pemilik_list() 
    pemilik_input = forms.ChoiceField(
        label='Identitas Pemilik',
        choices=list_pemilik,
        required=True,
        widget=forms.Select(attrs=attrs_select_pemilik)
    )

class Info_Barang_Level_Form(forms.Form):

    # untuk input persen royalti
    attrs_royal = {
        'class': 'form-control',
        'id': 'form_ID'
    }
    royal_input = forms.DecimalField(
        label='',
        required=True,
        widget=forms.NumberInput(attrs=attrs_royal)
    )

    # untuk harga sewa
    attrs_harga_sewa = {
        'class': 'form-control',
        'id': 'form_ID'
    }
    harga_sewa = forms.DecimalField(
        label='',
        required=True,
        widget=forms.NumberInput(attrs=attrs_harga_sewa)
    )

class Review_Form(forms.Form):
    # untuk input persen royalti
    attrs_review = {
        'class': 'form-control',
        'id': 'form_ID'
    }
    review_input = forms.CharField(
        label='',
        required=True,
        widget=forms.Textarea(attrs=attrs_review)
    )

barang/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db import connection
from .forms import Barang_Form, Info_Barang_Level_Form, Review_Form
from django.http import JsonResponse, HttpResponse, Http404, HttpResponseNotFound
import json
from urllib.parse import unquote
from django.views.decorators.csrf import csrf_exempt

response = {}


def create_barang(request):
    response['barangform'] = Barang_Form
    # buat fieldform sebanyak level, ambil dari db
    cursor = connection.cursor()
    sql = "SELECT COUNT(*) FROM toys_rent.level_keanggotaan"
    cursor.execute(sql)
    total_level = cursor.fetchall()[0][0]

    # ambil nama - nama level nya
    cursor = connection.cursor()
    sql = "SELECT nama_level FROM toys_rent.level_keanggotaan ORDER BY nama_level ASC"
    cursor.execute(sql)
    nama_nama_level = cursor.fetchall()
    nama_nama_level_clear = []
    for x in range(0, len(nama_nama_level)-1):
        for y in nama_nama_level[x]:
            nama_nama_level_clear.append(y)
    
    # bikin form sebanyak total_level
    formers = []
    for x in range(0, total_level-1):
        newInfo = Info_Barang_Level_Form
        formers.append([newInfo,nama_nama_level_clear[x]])
    response['formers'] = formers

    if request.method == 'POST':
        form = Barang_Form(request.POST or None)
        if (form.is_valid()):
            # ambil values dari POST request
            id_barang = request.POST.get("id_input")
            nama_item = request.POST.get("item_input")
            warna = request.POST.get("warna_input")
            warna = warna if warna != '' else None
            url_foto = request.POST.get("url_input")
            url_foto = url_foto if url_foto != '' else None
            kondisi = request.POST.get("kondisi_input")
            lama_penggunaan = request.POST.get("lama_penggunaan_input")
            lama_penggunaan = lama_penggunaan if lama_penggunaan != '' else None
            no_ktp_penyewa = request.POST.get("pemilik_input")

            # masukan ke db
            # perlu catch bila id sudah digunakan
            cursor = connection.cursor()
            sql = "INSERT INTO toys_rent.barang VALUES (%s, %s, %s, %s, %s, %s, %s);"
            cursor.execute(sql, (
                id_barang,
                nama_item,
                warna,
                url_foto,
                kondisi,
                lama_penggunaan,
                no_ktp_penyewa
            )
            )

            # redirect ke halaman paling akhir untuk nampilkan yang baru
            cursor = connection.cursor()
            sql = "SELECT COUNT(*) FROM toys_rent.barang"
            cursor.execute(sql)
            last_page = cursor.fetchall()[0][0]
            if (last_page % 10 == 0):
                last_page = last_page / 10
            else:
                last_page = last_page // 10 + 1
            last_page = int(last_page)
            site = unquote(reverse('barang:daftar_barang_pagination', kwargs={
                           'page_number': last_page}))
            return redirect(site)
    return render(request, 'create_barang.html', response)


def daftar_barang(request, page_number=1, sorter=""):
    response['barangform'] = Barang_Form
    # buat fieldform sebanyak level, ambil dari db
    cursor = connection.cursor()
    sql = "SELECT COUNT(*) FROM toys_rent.level_keanggotaan"
    cursor.execute(sql)
    total_level = cursor.fetchall()[0][0]

    # ambil nama - nama level nya
    cursor = connection.cursor()
    sql = "SELECT nama_level FROM toys_rent.level_keanggotaan ORDER BY nama_level ASC"
    cursor.execute(sql)
    nama_nama_level = cursor.fetchall()
    nama_nama_level_clear = []
    for x in range(0, len(nama_nama_level)-1):
        for y in nama_nama_level[x]:
            nama_nama_level_clear.append(y)
    
    # bikin form sebanyak total_level
    formers = []
    for x in range(0, total_level-1):
        newInfo = Info_Barang_Level_Form
        formers.append([newInfo,nama_nama_level_clear[x]])
    response['formers'] = formers
    
    if request.method == 'POST':
        form = Barang_Form(request.POST or None)
        if (form.is_valid()):
             # ambil values dari POST request
            id_barang = request.POST.get("id_input")
            nama_item = request.POST.get("item_input")
            warna = request.POST.get("warna_input")
            warna = warna if warna != '' else None
            url_foto = request.POST.get("url_input")
            url_foto = url_foto if url_foto != '' else None
            kondisi = request.POST.get("kondisi_input")
            lama_penggunaan = request.POST.get("lama_penggunaan_input")
            lama_penggunaan = lama_penggunaan if lama_penggunaan != '' else None
            no_ktp_penyewa = request.POST.get("pemilik_input")

            # masukan ke db
            # perlu catch bila id sudah digunakan
            cursor = connection.cursor()
            sql = "UPDATE toys_rent.barang SET nama_item = %s, warna = %s, url_foto = %s, kondisi = %s, lama_penggunaan = %s, no_ktp_penyewa = %s WHERE id_barang = %s;"
            cursor.execute(sql, (
                nama_item,
                warna,
                url_foto,
                kondisi,
                lama_penggunaan,
                no_ktp_penyewa,
                id_barang
            )
            )

            # redirect ke halaman awal
            site = unquote(reverse('barang:daftar_barang'))
            return redirect(site)

    return render(request, 'daftar_barang.html', response)


def detail_barang(request, id_barang = 1):
    cursor = connection.cursor()
    sql = "SELECT id_barang, nama_item, warna, url_foto, kondisi, lama_penggunaan, nama_lengkap FROM toys_rent.barang JOIN toys_rent.pengguna ON toys_rent.barang.no_ktp_penyewa = toys_rent.pengguna.no_ktp WHERE id_barang = CAST(" + str(id_barang) + " AS VARCHAR(10));"
    cursor.execute(sql)
    try:
        detail_info = cursor.fetchall()[0]
    except:
        return HttpResponseNotFound("Sorry, the page you looking for is invalid or not found\nHint: don't use address bar directly")
    response['id_barang'] = detail_info[0]
    response['nama_item'] = detail_info[1]
    response['warna'] = detail_info[2]
    response['url_foto'] = detail_info[3]
    response['kondisi'] = detail_info[4]
    response['lama_penggunaan'] = detail_info[5]
    response['nama_lengkap'] = detail_info[6]
    response['review_form'] = Review_Form
    # ambil review:
    cursor = connection.cursor()
    sql = "select nama_lengkap, review from toys_rent.pengguna p, toys_rent.barang_dikirim b, toys_rent.pengiriman k where k.no_resi = b.no_resi and p.no_ktp = k.no_ktp_anggota and id_barang = CAST(" + str(id_barang) + " AS VARCHAR(10));"
    cursor.execute(sql)
    response['daftar_review'] = cursor.fetchall()
    return render(request, 'detail_barang.html', response)


@csrf_exempt
def get_barang_list(request):
    sql = "SELECT id_barang, nama_item, warna, kondisi FROM toys_rent.barang"
    # ambil page number
    page_number = 1
    try:
        page_number = int(request.POST.get('page_number'))
    except:
        page_number = 1

    # cek sort type
    sorter = None
    try:
        sorter = request.POST.get('sorter')
        if (sorter != ""):
            sql += " ORDER BY " + sorter
    except:
        sorter = None

    # ambil list 10 barang, dimulai dari offset
    cursor = connection.cursor()
    if (page_number < 1):
        # TODO
        None
    offset = (page_number-1) * 10
    sql += " LIMIT 10 OFFSET " + str(offset)
    cursor.execute(sql)
    list_barang = cursor.fetchall()
    # ambil total pagination dari count
    cursor = connection.cursor()
    sql = "SELECT COUNT(*) FROM toys_rent.barang"
    cursor.execute(sql)
    total_pagination = cursor.fetchall()[0][0]
    if (total_pagination % 10 == 0):
        total_pagination = total_pagination / 10
    else:
        total_pagination = total_pagination // 10 + 1

    # return response
    response = {
        'result': list_barang,
        'pagination': total_pagination
    }
    return JsonResponse(response)


@csrf_exempt
def delete_barang(request):
    id_barang = request.POST.get("id")
    sql = "DELETE FROM toys_rent.barang WHERE id_barang = CAST(" + id_barang + " AS VARCHAR(10));"
    cursor = connection.cursor()
    cursor.execute(sql)
    return JsonResponse({'result': 'complete'})

barang/templates/create_barang.html
{% extends "base.html" %} {% load static %} {% block content %}
<!-- CONTENT -->
<div class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="roundedrec">
                <div class="insiderec">
                    <h2 class="judul">Penambahan Barang</h2>
                    <hr class="garis"> {% if barangform %}
                    <!-- untuk errors -->
                    {% if barangform.errors %}
                    <ul class="errors">
                        {% for error in barangform.errors %}
                        <li> {{ error }} </li>
                        {% endfor %}
                    </ul>
                    {% endif %} {% endif %}


                    <!-- untuk field dan label dari barangform -->
                    <form method="POST">
                        {% csrf_token %} {% for field in barangform %}
                        <div class="form-label-group">
                            <label class="font-weight-bold" for="{{ field.name }}">
                                {{ field.label }}
                            </label> {{ field }}
                        </div>
                        {% endfor %} {% if formers %}
                        <hr>
                        <b>Info Barang</b><br>
                        <ul>
                            {% for fieldform,nama in formers %}
                            <li>{{ nama }}<br> Persen royalty:
                                <div class="infobarang">
                                    {{ fieldform.royal_input }}
                                    <div class="infobarang2">
                                        (%)
                                    </div>
                                </div>
                                Harga sewa:
                                <div class="infobarang3">
                                    {{ fieldform.harga_sewa }}
                                    <div class="infobarang2">
                                        (Rupiah/minggu)
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <div class="submitditengah">
                            <button id="submit_barang" type="submit" class="button alert">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

barang/templates/detail_barang.html
{% extends "base.html" %} {% load static %} {% block content %}
<!-- CONTENT -->
<div class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="roundedrec">
                <div class="insiderec">
                    <a id="past_button" href="#"> <i class="fa fa-arrow-left back"></i></a>
                    <h2 class="judul">Detail Barang</h2>
                    <hr>
                    <div class="row">
                        <div class="col-sm-6 tengah">
                            <h4 class="blue">{{ nama_item }}</h4>
                        </div>
                        {% if request.session.role == "admin" %}
                        <div class="col-sm-6 kanan">
                            <button type="button" class="btn btn-primary update" data-toggle="modal" data-target="#id{{ id_barang }}">
                                <i class="fas fa-sync-alt"></i>
                            </button>
                            <div class="modal fade" id="id{{ id_barang }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="updatePesanan1">Update Barang</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body modalkiri">
                                            Apakah benar ingin <b>mengupdate</b> Barang {{ nama_item }} warna {{ warna }}?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                                            <button type="button" class="btn btn-primary btnagree" data-dismiss="modal">Ya, benar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="button" class="btn btn-primary delete" data-toggle="modal" data-target="#delete1">
                                <i class="fas fa-trash"></i>
                            </button>
                            <div class="modal fade" id="delete1" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deletePesanan1">Delete Barang</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body modalkiri">
                                            Apakah benar ingin <b>menghapus</b> Barang {{ nama_item }} warna {{ warna }}?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                                            <button type="button" class="btn btn-primary btnagree" data-dismiss="modal" onclick="del_barang({{ id_barang }})">Ya, benar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                    <hr class="garis">
                    <div class="row">
                        <div class="col-sm-6 tengah">
                            <p><b>ID Barang: </b>{{ id_barang }}</p>
                            <p><b>Nama Item: </b>{{ nama_item }}</p>
                            <p><b>Warna: </b>{{ warna }}</p>
                            <p><b>Kondisi: </b>{{ kondisi }}</p>
                            <p><b>Lama Penggunaan: </b>{{ lama_penggunaan }}</p>
                            <p><b>Pemilik/Penyewa: </b>{{ nama_lengkap }}</p>
                        </div>
                        <div class="col-sm-6 kanan">
                            <img src="{{ url_foto }}" alt="foto" width="300px" height="300px" srcset="">
                        </div>
                    </div>
                    <div class="submitditengah">
                        <button onclick="alert('not implemented')" type="submit" class="button alert">Pesan</button>
                    </div>
                    <hr class="garis2">
                    <p><b>Daftar Review</b></p>

                    <div class="row">
                        {% if request.session.role == "anggota" %}

                        <div class="col-sm-6 tengah">
                            <form method="POST">
                                {{ review_form }}
                                <div class="submitditengah">
                                    <button id="submit_review" type="submit" class="button alert" onclick="alert('not implemented')">Submit</button>
                                </div>
                            </form>
                        </div>
                        <div class="col-sm-6">
                            {% endif %} {% for nama, review in daftar_review %}
                            <table style="margin: 10px">
                                <tr>
                                    <th>
                                        Nama
                                    </th>
                                    <td>
                                        {{ nama }}
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        Review
                                    </th>
                                    <td>
                                        {{ review }}
                                    </td>
                                </tr>
                            </table>
                            {% endfor %}

                            <br> {% if request.session.role == "anggota" %}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var url_del_barang = "{% url 'barang:delete_barang' %}";

    $(document).ready(function() {
        $("#past_button").attr("href", document.referrer);
    });

    function del_barang(id_number) {
        $.ajax({
            type: "POST",
            url: url_del_barang,
            data: {
                id: id_number,
            },
            success: function(result) {
                back_to_past();
            },
            error: function(result) {
                alert('error');
            }
        });
    }

    function back_to_past() {
        window.location.replace = document.referrer;
    }
</script>
{% endblock %}