chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.chat, name='chat'),
    path('<tujuan>', views.chat, name='chat_tujuan'),
]

level/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('create_level', views.create_level, name='create_level'),
    path('daftar_level', views.daftar_level, name='daftar_level'),
    path('delete_level', views.delete_level, name='delete_level'),
    path('get-level-json/', views.get_level_json, name='get-level-json'),
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('register/', include('register.urls')),
    path('item/', include(('item.urls','item'),namespace='item')),
    path('profil/', include('profil.urls')),
    path('pesanan/', include(('pesanan.urls','pesanan'),namespace='pesanan')),
    path('level/', include(('level.urls','level'),namespace='level')),
    path('barang/', include(('barang.urls','barang'),namespace='barang')),
    path('chat/', include('chat.urls')),
]

level/models.py
from django.db import models

# Create your models here.

level/forms.py
from django import forms

class Level_Form(forms.Form):
    attrsnama = {
        'class' : 'form-control',
        'placeholder' : 'Masukan nama level',
        'id' : 'formNama'
    }

    attrsdeskripsi = {
        'class' : 'form-control',
        'placeholder' : 'Masukan deskripsi level',
        'id' : 'formDeskripsi'
    }

    attrspoin = {
        'class' : 'form-control',
        'placeholder' : 'Masukan minimal poin',
        'id' : 'formPoin'
    }

    nama = forms.CharField(label='Nama Level', required=True, max_length=30, widget=forms.TextInput(attrs=attrsnama))
    deskripsi = forms.CharField(label='Deskripsi', required=True, max_length=40, widget=forms.TextInput(attrs=attrsdeskripsi))
    poin = forms.IntegerField(label='Minimal Poin', required=True, widget=forms.TextInput(attrs=attrspoin))

level/views.py
from django.shortcuts import render
from django.db import connection
from .forms import Level_Form
from django.http import JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def create_level(request):
    response = {}
    response['levelform'] = Level_Form

    if request.method == 'POST':
        form = Level_Form(request.POST or None)
        if (form.is_valid()):
            nama = request.POST.get("nama")
            deskripsi = request.POST.get("deskripsi")
            poin = request.POST.get("poin")
            cursor = connection.cursor()
            sql = "INSERT INTO toys_rent.level_keanggotaan VALUES (%s, %s, %s);"
            cursor.execute(sql,(nama,poin,deskripsi))
            return render(request, 'daftar_level.html', response)
    return render(request,'create_level.html',response)

@csrf_exempt
def daftar_level(request):
    cursor = connection.cursor()
    sql = "select nama_level, deskripsi, minimum_poin from toys_rent.level_keanggotaan"
    cursor.execute(sql)
    list_level = cursor.fetchall()
    response = {'level' : list_level}
    return render(request,'daftar_level.html',response)

@csrf_exempt
def get_level_json(request):
    try:
        q = request.GET['q']
    except:
        q = ""
    print(q)
    if q == "":
        sql = "select nama_level, deskripsi, minimum_poin from toys_rent.level_keanggotaan"
    else:
        sql = "select nama_level, deskripsi, minimum_poin from toys_rent.level_keanggotaan where lower(nama_level) like %s"
    cursor = connection.cursor()
    q = '%%' + q + '%%' 
    q = q.lower()
    cursor.execute(sql, (q,))
    list_level = cursor.fetchall()
    dict_level = {}
    for i in list_level:
        b = i[0]
        dict_level[i[0]] = {}
        dict_level[i[0]]["nama_level"] = i[0]
        dict_level[i[0]]["deskripsi"] = i[1]
        dict_level[i[0]]["minimum_poin"] = i[2]
    return JsonResponse(dict_level)

@csrf_exempt
def delete_level(request):
    namanya = request.POST['namalevel']
    cursor = connection.cursor()
    sql = "delete from toys_rent.level_keanggotaan where nama_level = %s"
    cursor.execute(sql, (namanya,))
    connection.commit()
    return JsonResponse({})

level/templates/create_level.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!-- CONTENT -->
    <div class="content">
        <div class="row">
            <div class="col-sm-12">
                <div class="roundedrec">
                    <div class="insiderec">
                        <form action="" method="POST">
                        <h2 class="judul">Penambahan Level</h2>
                        <hr class="garis">
                        {% csrf_token %}
                        {{ levelform }}
                        <br>
                        <button id="submit_level" type="submit" class="button alert">Submit</button>
                    </form>            
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

level/templates/daftar_level.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!-- CONTENT -->
    <div class="content">
        <div class="row">
            <div class="col-sm-12">
                <div class="roundedrec">
                    <div class="insiderec">
                        <h2 class="judul2">Daftar Level</h2>
                        <input id="searchbar" type="text" name="" value="" placeholder="Search level..." style="display:inline">
                        <div class="table-responsive">
                            <table class="table center">    
                                <thead>
                                    <tr>
                                        <th scope="col">No</th>
                                        <th scope="col">Nama Level</th>
                                        <th scope="col">Deskripsi</th>
                                        <th scope="col">Minimum Poin</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody id="tabel-level">
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
    var get_level_json_url = "{% url 'level:get-level-json' %}";
    var url_delete_level = "{% url 'level:delete_level' %}"
    </script>
    <script type="text/javascript" src="{% static 'js/get-level.js' %}"></script>
    <script>
    function deleteFunction(nama){
    data = {
        "namalevel": nama,
      }
    console.log(nama)
    $.ajax({
        type: "POST",
        url: url_delete_level,
        data: data,
        success: function(result) {
            console.log(data);
            window.location.href="/level/daftar_level"
            
        },
        error: function(xhr) {
            console.log(xhr);        
        }
    });

}
    </script>
{% endblock %}