barang/urls.py
from django.urls import path
from .views import create_barang, daftar_barang, detail_barang, get_barang_list, delete_barang

urlpatterns = [
    path('create_barang', create_barang, name='create_barang'),
    path('daftar_barang/', daftar_barang, name='daftar_barang'),
    path('daftar_barang/?page=<int:page_number>', daftar_barang, name='daftar_barang_pagination'),
    path('detail_barang/<int:id_barang>', detail_barang, name='detail_barang_second'),
    path('get_barang_list', get_barang_list, name='get_barang_list'),
    path('delete_barang', delete_barang, name='delete_barang'),
]

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.chat, name='chat'),
    path('<tujuan>', views.chat, name='chat_tujuan'),
]

item/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('create_item/', views.create_item, name='create_item'),
    path('post_create_item/',views.post_create_item, name = 'postcreateitem'),
    path('daftar_item/', views.daftar_item, name='daftar_item'),
    path('delete-item/',views.delete_item, name = 'delete_item'),
    # path('kategori_values/',views.get_kategori_values, name = 'kategorivalues'),
    path('update_item/',views.update_item, name = 'update_item'),
]

level/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('create_level', views.create_level, name='create_level'),
    path('daftar_level', views.daftar_level, name='daftar_level'),
    path('delete_level', views.delete_level, name='delete_level'),
    path('get-level-json/', views.get_level_json, name='get-level-json'),
]

pesanan/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('create_pesanan', views.create_pesanan, name='create_pesanan'),
    path('daftar_pesanan', views.daftar_pesanan, name='daftar_pesanan'),
    path('delete_pesanan', views.delete_pesanan, name='delete_pesanan'),
    path('get-pesanan-json/', views.get_daftar_pesanan, name='get-daftar-pesanan'),
    path('post_create_pesanan/',views.post_create_pesanan, name = 'postcreatepesanan'),
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('register/', include('register.urls')),
    path('item/', include(('item.urls','item'),namespace='item')),
    path('profil/', include('profil.urls')),
    path('pesanan/', include(('pesanan.urls','pesanan'),namespace='pesanan')),
    path('level/', include(('level.urls','level'),namespace='level')),
    path('barang/', include(('barang.urls','barang'),namespace='barang')),
    path('chat/', include('chat.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Toys4Rent</title>
    <link rel="icon" href="{% static 'img/puzzle.png' %}" type="image/gif">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
</head>
<body>
	<!-- NAVBAR -->
	<nav class="navbar navbar-expand-lg navbar-light">
		<span class="navbar-brand"><img src="{% static 'img/puzzle.svg' %}" style="width:45px;"><span class="sr-only">(current)</span></span>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				{% if request.session.role == "admin" %}
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Item</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'item:create_item' %}">Create</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'item:daftar_item' %}">Daftar Item</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Barang</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'barang:create_barang' %}">Create</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'barang:daftar_barang' %}">Daftar Barang</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Level</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'level:create_level' %}">Create</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'level:daftar_level' %}">Daftar Level</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pesanan</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'pesanan:create_pesanan' %}">Create</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'pesanan:daftar_pesanan' %}">Daftar Pesanan</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pengiriman</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="#">Create</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="#">Daftar Pengiriman</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Review Barang</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="#">Create</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="#">Daftar Review Barang</a>
					</div>
				</li>
				{% elif request.session.role == "anggota" %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'item:daftar_item' %}">Daftar Item</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'barang:daftar_barang' %}">Daftar Barang</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pesanan</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'pesanan:create_pesanan' %}">Create</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'pesanan:daftar_pesanan' %}">Daftar Pesanan</a>
					</div>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pengiriman</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="#">Create</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="#">Daftar Pengiriman</a>
					</div>
				</li>
				{% endif %}
			</ul>
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'chat' %}">Chat</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'profil' %}">Profil</a>
				</li>
			</ul>
		</div>
	</nav>
	{% block content %}
	{% endblock %}
</body>
</html>

templates/landing.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Toys4Rent</title>
    <link rel="icon" href="{% static 'img/puzzle.png' %}" type="image/gif">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/landing.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
	<div class="landing">
		{% block content %}
		{% endblock %}
	</div>
</body>
</html>